POST http://localhost:8080/unprotected HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQxYjljNDJiZjFmODFlNzE0MzA2ZTFiIiwiZW1haWwiOiJ0d2dpMjIyM0BnbWFpbC5jb20iLCJpYXQiOjE2Nzk1MzExMDAsImV4cCI6MTY3OTYxNzUwMH0.w5H-pIXfoexb7vKxyDPKXdVhBFqUnaJGTky3G10BrJU"
}

###


POST http://localhost:8080/protected HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQxYjljNDJiZjFmODFlNzE0MzA2ZTFiIiwiZW1haWwiOiJ0d2dpMjIyM0BnbWFpbC5jb20iLCJpYXQiOjE2Nzk1MzExMDAsImV4cCI6MTY3OTYxNzUwMH0.w5H-pIXfoexb7vKxyDPKXdVhBFqUnaJGTky3G10BrJU"
}

###
