POST http://localhost:8080/unprotected HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQxYWVmZWE4MmY1MTljZmJkYmU5ZGQ4IiwiZW1haWwiOiJ0d2dpMjJAZ21haWwuY29tIiwiaWF0IjoxNjc5NDg2OTg1LCJleHAiOjE2Nzk1NzMzODV9.86LfAvajjnawqK8B1RYJ0djhTeerisoS_qYHSqGEnmo"
}

###


POST http://localhost:8080/protected HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQxYWVmZWE4MmY1MTljZmJkYmU5ZGQ4IiwiZW1haWwiOiJ0d2dpMjJAZ21haWwuY29tIiwiaWF0IjoxNjc5NDg2OTg1LCJleHAiOjE2Nzk1NzMzODV9.86LfAvajjnawqK8B1RYJ0djhTeerisoS_qYHSqGEnmo"
}

###
