GET http://localhost:8080/users HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/user HTTP/1.1
Content-Type: application/json

{
    "name": "Tuvshin",
    "email": "twgi@gmail.com",
    "createdOn" : "2023-03-15",
    "modifiedOn" : "2023-01-01",
    "lastLogin" : "2024-10-01"
}
###


DELETE  http://localhost:8080/user HTTP/1.1
Content-Type: application/json

{
   "_id": "6412753a9fef47916ca03d3a"
}


###


GET  http://localhost:8080/user?id=64126dfcf3893aee33d3652a HTTP/1.1
Content-Type: application/json



###



GET  http://localhost:8080/userbyemail?email=twgi@gmail.com HTTP/1.1
Content-Type: application/json

###



GET  http://localhost:8080/userGetEmail?email=twgi@gmail.com HTTP/1.1
Content-Type: application/json

###


PUT  http://localhost:8080/updateUser HTTP/1.1
Content-Type: application/json

###